version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 8081:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql