CREATE DATABASE blog;

\c blog

CREATE TABLE IF NOT EXISTS post (
    id SERIAL PRIMARY KEY,
    title VARCHAR (80) NOT NULL,
    body VARCHAR (5000) NOT NULL
);

CREATE TABLE IF NOT EXISTS tag (
    id SERIAL PRIMARY KEY,
    tag VARCHAR (20) NOT NULL,
    post_id INT NOT NULL,
    FOREIGN KEY (post_id)
        REFERENCES post (id)
);